### PR TITLE
Refactor appendCondition method for improved readability and null han…

### PR DESCRIPTION
**Pull request by joaomarcosjmos**
The appendCondition method has been updated to improve its readability and adherence to Clean Code principles. These modifications enhance code clarity and maintain the original functionality of the method. The updated code follows best practices and improves the overall maintainability of the codebase.

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by joaomarcosjmos** [comment]
Hello, I have the necessary credentials

**Review by otaviojava — APPROVED** [review]

**Comment by otaviojava** [comment]
@joaomarcosjmos 
That is great!
Thank you, did you check the AbstractMapperQuery in the [document](https://github.com/eclipse/jnosql/blob/main/jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/AbstractMapperQuery.java) and [graph](https://github.com/eclipse/jnosql/blob/main/jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/AbstractMapperQuery.java) module?

**Comment by joaomarcosjmos** [comment]
Okay @otaviojava, I can make this change in more of these two.

I will commit if possible.

**Comment by joaomarcosjmos** [comment]
@otaviojava, modifications done!
Thanks!

**Comment by dearrudam** [comment]
Congrats @joaomarcosjmos and thank you for the contribution!!!

**Pull request merged**
