### PR TITLE
Moved `jnosql-mapping-validation` to `jnosql-extensions`

### PR DESCRIPTION
**Pull request by dearrudam**
Ref: #358 
## Changes
 
 - Moved jnosql-mapping-validation to extensions
 - Update the change logs with the change
 - Move the read-me of validation to extensions.

### CODE REVIEW

**Comment by dearrudam** [comment]
@otaviojava, please, check this PR?

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by otaviojava** [comment]
@eliasnogueira does it impact your test enhancement?

We'll move the module validation to an extension.

**Comment by eliasnogueira** [comment]
Hey,
No 🎉

My starting point is at jnosql-communication-core

**Pull request merged**
