### PR TITLE
fix: fully thread safe DefaultEntitiesMetadata as it is @ApplicationScoped

### PR DESCRIPTION
**Pull request by m4ttek**
Should solve #508

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by dearrudam** [comment]
@m4ttek, thank you for your contribution! 

Oh, so sorry but I thought that you already knew the requirements to contribute with code to this project.

To accept this and new PRs, it's needed to complete some steps before:

- the commits that were provided by non-committers must have a Signed-off-by field in the footer indicating that the author is aware of the terms by which the contribution has been provided to the project, and
- non-committers must additionally have an Eclipse Foundation account and must have a signed Eclipse Contributor Agreement (ECA) on file. Get more info about it, please, take a look at our contribution guide: https://github.com/eclipse/jnosql/blob/main/CONTRIBUTING.adoc;

When these steps are completed, you'll be able to contribute with code to this project.

Meanwhile, I will apply these changes by myself in order to accelerate the resolution, okay? 

Again, thank you so much for your contributions!

**Comment by m4ttek** [comment]
@dearrudam thanks, I wasn't aware of these requirements. Anyway, you're free to introduce these changes to this project ;)

**Comment by otaviojava** [comment]
> @dearrudam thanks, I wasn't aware of these requirements. Anyway, you're free to introduce these changes to this project ;)

Thank you.
I still traveling.

I will check and move this PR forward, ASAP

**Pull request merged**
