### PR TITLE
Update Neo4J engine to use Java instead of Groovy

### PR DESCRIPTION
**Pull request by otaviojava**
Fix: https://github.com/eclipse/jnosql/issues/333

## Changes

* Update Apache Tinkerpop to version 3.6.2
* Fix the issue on the query parameter with `@` . E.g. ```g.V().hasLabel(@label```
* Remove the Grovy-gremlin parser
* Use Java Parser at Gremlin

:warning: I found a new issue on the Neo4J start-up. But I would like to fix another PR.
:bomb: We still need to fix this https://github.com/eclipse/jnosql/issues/335 to complete solution of Java 17 issue.

### CODE REVIEW

**Comment by otaviojava** [comment]
@dearrudam what do you think?

**Review by dearrudam — COMMENTED** [review]
Lol... here's the comment again:

@otaviojava there is some reason why to separate out the ANTL sources from the default `/jnosql-communication/jnosql-communication-query/src/main/antlr4 ` directory and put them into the `/antlr4` directory? 

Also, I think if we follow the default approach, we'll be able to eliminate some custom configurations in `/jnosql-communication/jnosql-communication-query/pom.xml` as below:
```xml
            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>${antlr4.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by otaviojava** [comment]
@dearrudam the directory is because the Graph-module needs to recompile the ANLTRs to the Apache Tinkerpop version.
Until they update their project is an option that we have.

**Comment by otaviojava** [comment]
@dearrudam to where?
lol

**Comment by dearrudam** [comment]
@otaviojava LOL! I've just edited that comment again!

**Comment by otaviojava** [comment]
@dearrudam I don't follow you on this point:
> Also, I think if we follow the default approach, we'll be able to eliminate some custom configurations in /jnosql-communication/jnosql-communication-query/pom.xml as below:

What do you mean?
Please, put the plugin as you wish or open a PR to my branch.

**Comment by dearrudam** [comment]
@otaviojava I've just opened this PR:  #336 to your branch.

**Comment by otaviojava** [comment]
Thank you @dearrudam

**Comment by otaviojava** [comment]
I'll include a CI with Java 17 to ensure it keeps working.

**Pull request merged**
