### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by Minitour**
Removed line duplicate.

### CODE REVIEW

**Comment by genie-jnosql** [comment]
Can one of the admins verify this patch?

**Comment by otaviojava** [comment]
thank you @Minitour

**Comment by Minitour** [comment]
@otaviojava Am I suppose to include the signed-off-by footer in the commit message?

**Comment by otaviojava** [comment]
Yes @Minitour

**Comment by Minitour** [comment]
I will close this one and create a new PR with a proper commit message.

**Pull request closed without merging**
